version: '2'
services:
  nginx:
    build: ./nginx
    links:
      - web:web
    ports:
      - "80:80"

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code:Z
      - /code/node_modules